### ISSUE TITLE
Swap step 3 and 4 in persisted user state restoration process (3.1.1)

### ISSUE THREAD

**Issue by majido** [majido/scroll-restoration-proposal#7]
From Olli:

```
   In 3.1.1 Persisted user state restoration steps 3 and 4 should probably 
   be swapped, since the current (3) may run scripts, and if those scripts 
   happen to use history API, they see wrong history.scrollRestoration value.
```

**Comment by majido** [comment]
I think this should be fine. 
@smaug----  I am curious which part of that step may run script. I was under the impression that only _popstate_ and _hashchange_ dispatch (which happen after 3.1.1) may run script.

**Comment by smaug----** [comment]
The spec is vague sure, but "for instance values of form fields"

**Comment by smaug----** [comment]
Though, perhaps no browser actually does that in this case and the spec is just wrong.

**Comment by majido** [comment]
Updated the order in the off-chance that any browser may decide to run script in that step.
