### ISSUE TITLE
Add this to the HTML Standard

### ISSUE THREAD

**Issue by domenic** [majido/scroll-restoration-proposal#9]
https://github.com/whatwg/html is now accepting pull requests! We'd love for you to be able to integrate this into the official HTML Standard, instead of having to monkey-patch a bunch of its algorithms.

Let us know if there's any way we can help with this!

**Comment by majido** [comment]
Woohoo! This is great. I will definitely send a pull request your way. I am not happy with the current monkey-patched spec.

**Comment by majido** [comment]
So I got a chance to write a first version:
https://github.com/majido/html/commit/4787a838177c2c8544fda907613a3ed48030a531

@domenic should I just send a pull request?

**Comment by domenic** [comment]
@majido yes, that'd be wonderful!
